# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LightSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightSDK

  target 'LightSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LightSDKUITests' do
    # Pods for testing
  end

end
